/// This file has messages for describing droplez-projects service

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: studio/projects/projects_v1.proto

package projects

import (
	common "github.com/droplez/droplez-go-proto/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DAW int32

const (
	DAW_DAW_UNSPECIFIED DAW = 0
	DAW_DAW_LOGIC_PRO   DAW = 1
	DAW_DAW_ABLETON     DAW = 2
	DAW_DAW_GARAGEBAND  DAW = 3
)

// Enum value maps for DAW.
var (
	DAW_name = map[int32]string{
		0: "DAW_UNSPECIFIED",
		1: "DAW_LOGIC_PRO",
		2: "DAW_ABLETON",
		3: "DAW_GARAGEBAND",
	}
	DAW_value = map[string]int32{
		"DAW_UNSPECIFIED": 0,
		"DAW_LOGIC_PRO":   1,
		"DAW_ABLETON":     2,
		"DAW_GARAGEBAND":  3,
	}
)

func (x DAW) Enum() *DAW {
	p := new(DAW)
	*p = x
	return p
}

func (x DAW) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DAW) Descriptor() protoreflect.EnumDescriptor {
	return file_studio_projects_projects_v1_proto_enumTypes[0].Descriptor()
}

func (DAW) Type() protoreflect.EnumType {
	return &file_studio_projects_projects_v1_proto_enumTypes[0]
}

func (x DAW) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DAW.Descriptor instead.
func (DAW) EnumDescriptor() ([]byte, []int) {
	return file_studio_projects_projects_v1_proto_rawDescGZIP(), []int{0}
}

type ProjectId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProjectId) Reset() {
	*x = ProjectId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_projects_projects_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectId) ProtoMessage() {}

func (x *ProjectId) ProtoReflect() protoreflect.Message {
	mi := &file_studio_projects_projects_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectId.ProtoReflect.Descriptor instead.
func (*ProjectId) Descriptor() ([]byte, []int) {
	return file_studio_projects_projects_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ProjectId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata *ProjectMeta `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ProjectInfo) Reset() {
	*x = ProjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_projects_projects_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectInfo) ProtoMessage() {}

func (x *ProjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_studio_projects_projects_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectInfo.ProtoReflect.Descriptor instead.
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return file_studio_projects_projects_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectInfo) GetId() *ProjectId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ProjectInfo) GetMetadata() *ProjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProjectMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Daw         DAW    `protobuf:"varint,2,opt,name=daw,proto3,enum=projects.DAW" json:"daw,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Public      bool   `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
	Bpm         int32  `protobuf:"varint,5,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Key         string `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Genre       string `protobuf:"bytes,7,opt,name=genre,proto3" json:"genre,omitempty"`
	Template    bool   `protobuf:"varint,8,opt,name=template,proto3" json:"template,omitempty"`
}

func (x *ProjectMeta) Reset() {
	*x = ProjectMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_projects_projects_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMeta) ProtoMessage() {}

func (x *ProjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_studio_projects_projects_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMeta.ProtoReflect.Descriptor instead.
func (*ProjectMeta) Descriptor() ([]byte, []int) {
	return file_studio_projects_projects_v1_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectMeta) GetDaw() DAW {
	if x != nil {
		return x.Daw
	}
	return DAW_DAW_UNSPECIFIED
}

func (x *ProjectMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectMeta) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *ProjectMeta) GetBpm() int32 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *ProjectMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProjectMeta) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ProjectMeta) GetTemplate() bool {
	if x != nil {
		return x.Template
	}
	return false
}

type ListOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paging *common.Paging `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *ListOptions) Reset() {
	*x = ListOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_projects_projects_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptions) ProtoMessage() {}

func (x *ListOptions) ProtoReflect() protoreflect.Message {
	mi := &file_studio_projects_projects_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptions.ProtoReflect.Descriptor instead.
func (*ListOptions) Descriptor() ([]byte, []int) {
	return file_studio_projects_projects_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ListOptions) GetPaging() *common.Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

var File_studio_projects_projects_v1_proto protoreflect.FileDescriptor

var file_studio_projects_projects_v1_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x1a, 0x16, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x65, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x23, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xd2, 0x01, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x03, 0x64, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x44, 0x41, 0x57, 0x52, 0x03, 0x64, 0x61, 0x77, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x70, 0x6d, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x62, 0x70, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x35,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x0a,
	0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x2a, 0x52, 0x0a, 0x03, 0x44, 0x41, 0x57, 0x12, 0x13, 0x0a, 0x0f,
	0x44, 0x41, 0x57, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x41, 0x57, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x43, 0x5f, 0x50,
	0x52, 0x4f, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x41, 0x57, 0x5f, 0x41, 0x42, 0x4c, 0x45,
	0x54, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x41, 0x57, 0x5f, 0x47, 0x41, 0x52,
	0x41, 0x47, 0x45, 0x42, 0x41, 0x4e, 0x44, 0x10, 0x03, 0x32, 0x9c, 0x02, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x30,
	0x01, 0x12, 0x35, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x7a, 0x2f, 0x64,
	0x72, 0x6f, 0x70, 0x6c, 0x65, 0x7a, 0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_studio_projects_projects_v1_proto_rawDescOnce sync.Once
	file_studio_projects_projects_v1_proto_rawDescData = file_studio_projects_projects_v1_proto_rawDesc
)

func file_studio_projects_projects_v1_proto_rawDescGZIP() []byte {
	file_studio_projects_projects_v1_proto_rawDescOnce.Do(func() {
		file_studio_projects_projects_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_studio_projects_projects_v1_proto_rawDescData)
	})
	return file_studio_projects_projects_v1_proto_rawDescData
}

var file_studio_projects_projects_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_studio_projects_projects_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_studio_projects_projects_v1_proto_goTypes = []interface{}{
	(DAW)(0),                    // 0: projects.DAW
	(*ProjectId)(nil),           // 1: projects.ProjectId
	(*ProjectInfo)(nil),         // 2: projects.ProjectInfo
	(*ProjectMeta)(nil),         // 3: projects.ProjectMeta
	(*ListOptions)(nil),         // 4: projects.ListOptions
	(*common.Paging)(nil),       // 5: common.Paging
	(*common.EmptyMessage)(nil), // 6: common.EmptyMessage
}
var file_studio_projects_projects_v1_proto_depIdxs = []int32{
	1, // 0: projects.ProjectInfo.id:type_name -> projects.ProjectId
	3, // 1: projects.ProjectInfo.metadata:type_name -> projects.ProjectMeta
	0, // 2: projects.ProjectMeta.daw:type_name -> projects.DAW
	5, // 3: projects.ListOptions.paging:type_name -> common.Paging
	3, // 4: projects.Projects.Create:input_type -> projects.ProjectMeta
	2, // 5: projects.Projects.Update:input_type -> projects.ProjectInfo
	1, // 6: projects.Projects.Get:input_type -> projects.ProjectId
	4, // 7: projects.Projects.List:input_type -> projects.ListOptions
	2, // 8: projects.Projects.Delete:input_type -> projects.ProjectInfo
	2, // 9: projects.Projects.Create:output_type -> projects.ProjectInfo
	2, // 10: projects.Projects.Update:output_type -> projects.ProjectInfo
	2, // 11: projects.Projects.Get:output_type -> projects.ProjectInfo
	2, // 12: projects.Projects.List:output_type -> projects.ProjectInfo
	6, // 13: projects.Projects.Delete:output_type -> common.EmptyMessage
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_studio_projects_projects_v1_proto_init() }
func file_studio_projects_projects_v1_proto_init() {
	if File_studio_projects_projects_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_studio_projects_projects_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_projects_projects_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_projects_projects_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_projects_projects_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_studio_projects_projects_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studio_projects_projects_v1_proto_goTypes,
		DependencyIndexes: file_studio_projects_projects_v1_proto_depIdxs,
		EnumInfos:         file_studio_projects_projects_v1_proto_enumTypes,
		MessageInfos:      file_studio_projects_projects_v1_proto_msgTypes,
	}.Build()
	File_studio_projects_projects_v1_proto = out.File
	file_studio_projects_projects_v1_proto_rawDesc = nil
	file_studio_projects_projects_v1_proto_goTypes = nil
	file_studio_projects_projects_v1_proto_depIdxs = nil
}
